### PR TITLE
Return ofVec3f copy in Ray::getEnd()

### LINKED ISSUE #9: Ray::getEnd() returns stack object by ref
[Here](https://github.com/elliotwoods/ofxRay/blob/master/src/ofxRay/Ray.cpp#L181-L183)

### PR DESCRIPTION
**Pull request by admsyn**
Fixes #9 and ruins [visual symmetry of ofxRay.h](https://github.com/admsyn/ofxRay/blob/855de50b1c9a69d930d573588666092ef8141d55/src/ofxRay/Ray.h#L43-L45) :)

### CODE REVIEW

**Comment by elliotwoods** [comment]
gah! i just did that :)

**Comment by elliotwoods** [comment]
could you try the head version?

**Comment by admsyn** [comment]
Looks good :) Doesn't compile for me as-is, though, just due to the `getTextureReference()` thing from #8

**Comment by elliotwoods** [comment]
so head now
 compiles and doesn't complain?

**Comment by admsyn** [comment]
yepp!

**Pull request closed without merging**
