### PR TITLE
FIX ray-plane intersect nan distance

### PR DESCRIPTION
**Pull request by fyoudine**

### CODE REVIEW

**Comment by elliotwoods** [comment]
hey! Thanks for these!
Personally I'd name AABB as BoundingBox so that people can more easily understand it.
What do you think?

**Comment by fyoudine** [comment]
At last maybe you should name it AxisAlignedBoundingBox in case you
implement OBB 😉

Le mar. 18 févr. 2020 à 02:18, Elliot Woods <notifications@github.com> a
écrit :

**Comment by elliotwoods** [comment]
aha! 
I didn't catch that point. Yes maybe your suggestion is best.

**Comment by fyoudine** [comment]
For convenience you can add

typedef ofxRay::AABB ofAABB;
typedef ofxRay::AABB ofBoundingBox;

have you notice the "FIX ray-plane intersect nan distance" commit as well ?

**Comment by elliotwoods** [comment]
Yes I noticed both
I won't have time to test at the moment sorry so I need to trust you :)
Let me merge these for now

**Pull request merged**
