### PR TITLE
Refactoring addon's source to use glm instead of ofVector maths

### PR DESCRIPTION
**Pull request by roymacdonald**
Hi Elliot! I just refactored this addon to use glm instead of ofVec maths.
I have not tested it thoroughly yet but at least the maths look fine to me and it compiles.
Let me know what you think. 
I still need to update the examples.

### CODE REVIEW

**Comment by elliotwoods** [comment]
hello!
wonderful to see this
sadly i'm still living in pre-glm land
i'll move myself to a branch and make this one master
Is it ready for prime time?

**Comment by roymacdonald** [comment]
Hi.
it would be cool if you move it to master but it is not ready yet! I haven't updated the examples and I need to double check that all the math is being done properly. I'll be pushing soon and let you know once it is ready.

**Comment by elliotwoods** [comment]
Ok great. 
Then I will wait for your check.

Thank you so much for putting the time in to update this!

**Comment by roymacdonald** [comment]
No problem! glad to help.

I was checking the examples and a few of these make use of ofxGrabCam. Although when I like ofxGrabCam I feel that it is not a necesary thing to have it. I think it would be more neat just to use ofEasyCam, thus not having to rely on another addon just to run the examples. What do you think?

**Comment by elliotwoods** [comment]
Yes feel free to rip it out

**Comment by elliotwoods** [comment]
hey! i presume this is good to go

**Comment by elliotwoods** [comment]
I've tagged the existing version as 0.9.8 for anybody who needs it, merging now. Will test here

**Comment by elliotwoods** [comment]
THANK YOU !!! 🙇‍♀️🙇‍♂️

**Comment by roymacdonald** [comment]
Hi. I had to leave this on a standby as I had to dive into something else.
As far as I can remember, it should be all fine, maybe one example still needs to be updated.
I will have time next week. I'll double check it by then and let you know.
cheers!

**Comment by elliotwoods** [comment]
I tested here on 0.10.0 (you've inspired me to upgrade) and only one example needed updating (mostly to remove ofxGrabCam) - which is now done and pushed

**Comment by roymacdonald** [comment]
lol. great to know that I inspired you to upgrade. 
I kinda hated glm at the begining but now I like it, specially the C/C++ to glsl compatibility.
I am still super busy so I will take a look at all this next week.
Take care.

**Pull request merged**
