### PR TITLE
Glm refactor

### PR DESCRIPTION
**Pull request by roymacdonald**
I fixed the maths in `Projector::castCoordinates(const vector<glm::vec2>& xy, vector<Ray>& rays) const {`
now the projector example works as expected

### CODE REVIEW

**Comment by elliotwoods** [comment]
oh interesting
I was just doing a project which succeeded casting coordinates
but i was using the `castCoordinate` and here you're checking `castCoodinates`
And yes - your changes are the same as mine (but to the other function) so all checks out :)

**Comment by roymacdonald** [comment]
yes. there was a few missing things in `castCoordinates`.
Probably it would be less error prone to have an auxiliary function that would do the math while still having the optimizations that `castCoordinates` has. what do you think?

**Comment by elliotwoods** [comment]
in theory it's faster to do it this way - but i've been getting more confident of compilers recently ;)

anyway it works now - let's not touch it for another 5 years haha

**Comment by elliotwoods** [comment]
a quick note - the next big update to ofxRay is likely to be templating everything like glm
the main advantage of that is that we can then use ofxRay with auto-differentiation solvers like Ceres, which would make many many more calibration problems tenable

**Comment by roymacdonald** [comment]
well count with me for that big update. 
I didn't know about Ceres but it looks quite nice. I'll get a bit more into it.
Cheers

**Comment by elliotwoods** [comment]
I'm working on:
https://github.com/elliotwoods/ofxCeres

**Comment by roymacdonald** [comment]
nice. I'll take a look at it. what are you using it for specifically?

**Pull request merged**
